---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: petclinic
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v1.0.*
spec:
  releaseName: petclinic
  chart:
    git: https://github.com/anqingxu/spring-petclinic-helm
    ref: master
    path: spring-petclinic
  values:
    replicaCount: 7
    image:
      repository: anqingxu/petclinic
      tag: v1.0.13
