apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: "1.27.4"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.4.5
    - name: job-dsl
      version: "1.76"
    - name: configuration-as-code
      version: "1.45"
    - name: kubernetes-credentials-provider
      version: 0.12.1
    plugins:
      - name: github
        version: 1.32.0
      - name: pipeline-maven
        version: 3.9.3
      - name: docker-workflow
        version: 1.24
    containers:
    - name: jenkins-master
      image: anqingxu/jenkins-maven:v1.0.1
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 10
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator-petclinic-example
    targets: "cicd/jobs/*.jenkins"
    description: "Build petclinic using Jenkins operator"
    repositoryBranch: master
    repositoryUrl: https://github.com/anqingxu/petclinic.git
    githubPushTrigger: false
